version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "weekly"
    groups:
      docker-client-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      docker-client-major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "weekly"
    groups:
      docker-server-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      docker-server-major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    groups:
      client-npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      client-npm-major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "nuget"
    directory: "/server"
    schedule:
      interval: "weekly"
    groups:
      server-nuget-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      server-nuget-major:
        patterns:
          - "*"
        update-types:
          - "major"
