/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseSlugRouteImport } from './routes/course/$slug'
import { Route as DegreeCourseSlugRouteImport } from './routes/degree-course/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugRoute = CourseSlugRouteImport.update({
  id: '/course/$slug',
  path: '/course/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DegreeCourseSlugRoute = DegreeCourseSlugRouteImport.update({
  id: '/degree-course/$slug',
  path: '/degree-course/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/course/$slug': typeof CourseSlugRoute
  '/degree-course/$slug': typeof DegreeCourseSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/course/$slug': typeof CourseSlugRoute
  '/degree-course/$slug': typeof DegreeCourseSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/course/$slug': typeof CourseSlugRoute
  '/degree-course/$slug': typeof DegreeCourseSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/course/$slug' | '/degree-course/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/course/$slug' | '/degree-course/$slug'
  id: '__root__' | '/' | '/course/$slug' | '/degree-course/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseSlugRoute: typeof CourseSlugRoute
  DegreeCourseSlugRoute: typeof DegreeCourseSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$slug': {
      id: '/course/$slug'
      path: '/course/$slug'
      fullPath: '/course/$slug'
      preLoaderRoute: typeof CourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/degree-course/$slug': {
      id: '/degree-course/$slug'
      path: '/degree-course/$slug'
      fullPath: '/degree-course/$slug'
      preLoaderRoute: typeof DegreeCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseSlugRoute: CourseSlugRoute,
  DegreeCourseSlugRoute: DegreeCourseSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
