/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as DegreeCoursesSlugRouteImport } from './routes/degree-courses/$slug'
import { Route as LecturersSlugRouteImport } from './routes/lecturers/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DegreeCoursesSlugRoute = DegreeCoursesSlugRouteImport.update({
  id: '/degree-courses/$slug',
  path: '/degree-courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturersSlugRoute = LecturersSlugRouteImport.update({
  id: '/lecturers/$slug',
  path: '/lecturers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/degree-courses/$slug': typeof DegreeCoursesSlugRoute
  '/lecturers/$slug': typeof LecturersSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/degree-courses/$slug': typeof DegreeCoursesSlugRoute
  '/lecturers/$slug': typeof LecturersSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/degree-courses/$slug': typeof DegreeCoursesSlugRoute
  '/lecturers/$slug': typeof LecturersSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses/$slug'
    | '/degree-courses/$slug'
    | '/lecturers/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/courses/$slug' | '/degree-courses/$slug' | '/lecturers/$slug'
  id:
    | '__root__'
    | '/'
    | '/courses/$slug'
    | '/degree-courses/$slug'
    | '/lecturers/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  DegreeCoursesSlugRoute: typeof DegreeCoursesSlugRoute
  LecturersSlugRoute: typeof LecturersSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/degree-courses/$slug': {
      id: '/degree-courses/$slug'
      path: '/degree-courses/$slug'
      fullPath: '/degree-courses/$slug'
      preLoaderRoute: typeof DegreeCoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturers/$slug': {
      id: '/lecturers/$slug'
      path: '/lecturers/$slug'
      fullPath: '/lecturers/$slug'
      preLoaderRoute: typeof LecturersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  DegreeCoursesSlugRoute: DegreeCoursesSlugRoute,
  LecturersSlugRoute: LecturersSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
