/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MockUsosRouteImport } from './routes/mock-usos'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as DegreeCoursesSlugRouteImport } from './routes/degree-courses/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MockUsosRoute = MockUsosRouteImport.update({
  id: '/mock-usos',
  path: '/mock-usos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DegreeCoursesSlugRoute = DegreeCoursesSlugRouteImport.update({
  id: '/degree-courses/$slug',
  path: '/degree-courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mock-usos': typeof MockUsosRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/degree-courses/$slug': typeof DegreeCoursesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mock-usos': typeof MockUsosRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/degree-courses/$slug': typeof DegreeCoursesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/mock-usos': typeof MockUsosRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/degree-courses/$slug': typeof DegreeCoursesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mock-usos'
    | '/profile'
    | '/courses/$slug'
    | '/degree-courses/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mock-usos'
    | '/profile'
    | '/courses/$slug'
    | '/degree-courses/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/mock-usos'
    | '/_authenticated/profile'
    | '/courses/$slug'
    | '/degree-courses/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  MockUsosRoute: typeof MockUsosRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  DegreeCoursesSlugRoute: typeof DegreeCoursesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-usos': {
      id: '/mock-usos'
      path: '/mock-usos'
      fullPath: '/mock-usos'
      preLoaderRoute: typeof MockUsosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/degree-courses/$slug': {
      id: '/degree-courses/$slug'
      path: '/degree-courses/$slug'
      fullPath: '/degree-courses/$slug'
      preLoaderRoute: typeof DegreeCoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  MockUsosRoute: MockUsosRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  DegreeCoursesSlugRoute: DegreeCoursesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
