services:
  client:
    image: ghcr.io/${GITHUB_REPOSITORY:-akai-org/put-wiki}/client:${CLIENT_TAG:-latest}

  server:
    image: ghcr.io/${GITHUB_REPOSITORY:-akai-org/put-wiki}/server:${SERVER_TAG:-latest}
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
