using System.Threading.Tasks;

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.OpenApi;

using Scalar.AspNetCore;

namespace Presentation.Extensions;

public static class PresentationConfiguration
{
    private static IServiceCollection AddPutWikiOpenApi(this IServiceCollection services)
    {
        services.AddOpenApi("v1", options =>
        {
            options.AddScalarTransformers();

            options.AddDocumentTransformer((document, _, _) =>
            {
                document.Info = new OpenApiInfo
                {
                    Title = "PutWiki API documentation",
                    Version = "v1"
                };
                return Task.CompletedTask;
            });

            options.AddSchemaTransformer((schema, context, cancellationToken) =>
            {
                if (context.JsonTypeInfo.Type == typeof(ProblemDetails) && schema.Properties != null)
                {
                    if (schema.Properties.TryGetValue("type", out var typeSchema))
                        typeSchema.Description = "A URI reference that identifies the problem type. Can be sometimes just thrown exception type.";

                    if (schema.Properties.TryGetValue("title", out var titleSchema))
                        titleSchema.Description = "A short, human-readable summary of the problem type.";

                    if (schema.Properties.TryGetValue("status", out var statusSchema))
                        statusSchema.Description = "The HTTP status code generated by the origin server for this occurrence of the problem";

                    if (schema.Properties.TryGetValue("detail", out var detailSchema))
                        detailSchema.Description = "A human-readable explanation specific to this occurrence of the problem.";

                    if (schema.Properties.TryGetValue("instance", out var instanceSchema))
                        instanceSchema.Description = "A URI reference that identifies the specific request path.";

                    schema.Properties["errors"] = new OpenApiSchema
                    {
                        Type = JsonSchemaType.Array,
                        Items = new OpenApiSchema { Type = JsonSchemaType.String },
                        Description = "An array of all detailed error messages."
                    };
                }
                return Task.CompletedTask;
            });
        });

        return services;
    }

    public static IApplicationBuilder UsePutWikiOpenApiDocs(this WebApplication app)
    {
        if (app.Environment.IsDevelopment())
        {
            app.MapOpenApi("/docs/{documentName}.json");
            app.MapScalarApiReference("/docs", options =>
            {
                options
                    .WithOpenApiRoutePattern("/docs/{documentName}.json")
                    .AddDocument("v1")
                    .WithTitle("PutWiki API documentation")
                    .ForceDarkMode()
                    .SortTagsAlphabetically()
                    .SortOperationsByMethod()
                    .DisableAgent()
                    .DisableTelemetry()
                    .HideDeveloperTools()
                    .WithDefaultHttpClient(ScalarTarget.JavaScript, ScalarClient.Axios);
            });
        }
        return app;
    }

    public static IServiceCollection AddWebServices(this IServiceCollection services)
    {
        services.AddControllers();

        services.AddProblemDetails(options =>
        {
            options.CustomizeProblemDetails = context =>
            {
                context.ProblemDetails.Extensions.Remove("traceId");

                context.ProblemDetails.Instance =
                    $"{context.HttpContext.Request.Method} {context.HttpContext.Request.Path}";
            };
        });

        services.AddPutWikiOpenApi();

        return services;
    }
}