server {
    listen 80;
    server_name _;

    error_page 503 @maintenance;

    location / {
        return 503;
    }

    location @maintenance {
        root /usr/share/nginx/html;
        rewrite ^(.*)$ /index.html break;
    }
}
