import { http, HttpResponse } from 'msw';

// Mocks auth contract of the backend (branch 65-jwt-generation):
// - GET /api/auth/callback sets httpOnly `auth_token` cookie with JWT
// - GET /api/user/profile reads the cookie and returns 401 when it's missing, invalid or expired
// MSW keeps mocked cookies in its own cookie jar (persisted in localStorage under `__msw-cookie-store__`),
// so they are sent to handlers but, like real httpOnly cookies, are not visible in document.cookie.

const AUTH_COOKIE_NAME = 'auth_token';
const MOCK_USER_ID = '01977f3a-5c2e-7000-8000-000000000001';
// Backend default is 24 hours. Set VITE_MOCK_TOKEN_TTL_MINUTES=1 to test session expiration.
const TOKEN_TTL_MINUTES = Number(import.meta.env.VITE_MOCK_TOKEN_TTL_MINUTES) || 1440;

interface MockJwtPayload {
  sub: string;
  exp: number;
}

function toBase64Url(value: object): string {
  return btoa(JSON.stringify(value)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

// Same claims as tokens generated by backend's JwtService. Signature is fake - mocks don't verify it.
function createMockJwt(userId: string, expiresAt: Date): string {
  const now = Math.floor(Date.now() / 1000);
  const header = { alg: 'HS256', typ: 'JWT' };
  const payload = {
    nameid: userId,
    sub: userId,
    nbf: now,
    exp: Math.floor(expiresAt.getTime() / 1000),
    iss: 'PutWiki',
    aud: 'PutWikiClient',
  };

  return `${toBase64Url(header)}.${toBase64Url(payload)}.mock-signature`;
}

function decodeMockJwt(token: string): MockJwtPayload | null {
  try {
    const payload = JSON.parse(atob(token.split('.')[1].replace(/-/g, '+').replace(/_/g, '/')));
    return typeof payload.sub === 'string' && typeof payload.exp === 'number' ? payload : null;
  } catch {
    return null;
  }
}

// ASP.NET JwtBearer challenge: empty body with WWW-Authenticate header
function unauthorized(wwwAuthenticate = 'Bearer') {
  return new HttpResponse(null, { status: 401, headers: { 'WWW-Authenticate': wwwAuthenticate } });
}

export const authHandlers = [
  // In the real flow USOS redirects the browser here. With mocks it's called by the fake USOS page (/mock-usos).
  http.get('/api/auth/callback', ({ request }) => {
    const { searchParams } = new URL(request.url);

    if (!searchParams.get('oauth_token') || !searchParams.get('oauth_verifier')) {
      return HttpResponse.json(
        {
          title: 'One or more validation errors occurred.',
          status: 400,
          errors: { oauthVerifier: ['The oauth_verifier field is required.'] },
        },
        { status: 400, headers: { 'Content-Type': 'application/problem+json' } }
      );
    }

    const expiresAt = new Date(Date.now() + TOKEN_TTL_MINUTES * 60 * 1000);
    const token = createMockJwt(MOCK_USER_ID, expiresAt);

    return new HttpResponse(null, {
      status: 200,
      headers: {
        'Set-Cookie': `${AUTH_COOKIE_NAME}=${token}; Expires=${expiresAt.toUTCString()}; Path=/; HttpOnly; SameSite=Lax`,
      },
    });
  }),

  http.get('/api/user/profile', ({ cookies }) => {
    const token = cookies[AUTH_COOKIE_NAME];
    if (!token) {
      return unauthorized();
    }

    const payload = decodeMockJwt(token);
    if (!payload) {
      return unauthorized('Bearer error="invalid_token"');
    }

    if (payload.exp * 1000 <= Date.now()) {
      return unauthorized(
        `Bearer error="invalid_token", error_description="The token expired at '${new Date(payload.exp * 1000).toUTCString()}'"`
      );
    }

    return HttpResponse.json({
      userId: payload.sub,
      isAuthenticated: true,
      authenticationType: 'AuthenticationTypes.Federation',
    });
  }),

  // TODO: not implemented in backend yet - proposed contract. Removes the cookie by setting past expiration date.
  http.post('/api/auth/logout', () => {
    return new HttpResponse(null, {
      status: 204,
      headers: {
        'Set-Cookie': `${AUTH_COOKIE_NAME}=; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Path=/; HttpOnly; SameSite=Lax`,
      },
    });
  }),
];
