name: Deploy put-wiki to Raspberry Pi

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Fetch new code, pull images and run
        run: |
          cd /home/joszko/put-wiki

          git fetch origin --tags

          git checkout -f tags/${{ github.event.release.tag_name }}

          TAG=${{ github.event.release.tag_name }} docker compose -f compose.yml -f compose.prod.yml up -d
